[package]
name = "quiver-chat"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "quiver-chat"
path = "src/main.rs"

[dependencies]
quiver-config = { workspace = true }
quiver-twitch = { workspace = true }

tokio = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
indexmap = { workspace = true }
ron = { workspace = true }
schemars = { workspace = true }
axum = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }

lightningcss = { workspace = true }
notify = { workspace = true }
notify-debouncer-full = { workspace = true }
tokio-util = { workspace = true }
reqwest = { workspace = true }
regex = { workspace = true }
sha2 = { workspace = true }
hex = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
tempfile = "3"
serde_json = { workspace = true }

[lints]
workspace = true
